### ISSUE TITLE
Advertised "AeroService" and "AeroController" types are missing

### ISSUE THREAD

**Issue by cmumme** [NightrainsRbx/RobloxLsp#117]
The types advertised on the DevForum post are completely missing, both in practice, and in this GitHub repo.
https://devforum.roblox.com/t/roblox-lsp-full-intellisense-for-roblox-and-luau/717745
![image](https://user-images.githubusercontent.com/61283706/142661614-9f3d12b0-5a15-40cf-a16e-042f93b2fc7c.png)

**Comment by cmumme** [comment]
![image](https://user-images.githubusercontent.com/61283706/142661989-bf99bd18-4486-40e6-8396-da927720a640.png)
It appears to be there in 0.14.1, though. Why was it removed?

**Comment by cmumme** [comment]
https://github.com/NightrainsRbx/RobloxLsp/commit/1d654d19eaedd901a2fd80308637f9e76d51c0c3 This commit removed AeroGameFramework typings.

**Comment by NightrainsRbx** [comment]
They got removed because the language server got fully refactored, the correct way to say it would be that they were not re-implemented.

I will implement them in the future, but at the moment I don't recommend you to switch back to v0.15.11, you can add your own types to `robloxLsp.workspace.library` and have most of the functionality, for example, in the settings set the path of a .lua file containing:

```lua
export type AeroService = {
    RegisterEvent: (self: AeroService, eventName: string) -> (),
    Services: {
        xd: typeof(require(game.ReplicatedStorage.xd))
    }
}
```
And the type AeroService will be available across all your workspace.

**Comment by cmumme** [comment]
Oh, that's nice to know. Thank you!
