### ISSUE TITLE
LSP doesn't activate

### ISSUE THREAD

**Issue by techs-sus** [NightrainsRbx/RobloxLsp#155]
The LSP extension doesn't activate, unless you downgrade to 1.5.6 and reload the window. Please add a way to activate the extension manually.

**Comment by NightrainsRbx** [comment]
If Roblox LSP doesn't activate it's a bug, you should provide more details about the problem. Check if you got any error notifications, or check VSCode's Output.

There is no need to add a way to activate the extension manually, since this is a bug. The extension should activate automatically when you open a .lua/luau file in your workspace.

**Comment by techs-sus** [comment]
~~When I open a .lua/luau file in my workspace (on Artix) the extension doesn't activate.~~
There is a fix: installing directly from the extension page.
I think the extension released by open-vsx is corrupt (the file size is way smaller than the regular extension).
## Fix
1. Install the latest version from [the version history page](https://marketplace.visualstudio.com/items?itemName=Nightrains.robloxlsp&ssr=false#version-history).
2. Install the extension from vsix with:
```bash
code --install-extension /path/to/vsix --force
```
or, with:
```bash
codium --install-extension /path/to/vsix --force
```
if you are using VSCodium!

Sorry for wasting your time though. Really should've done more research before making this issue. 😔
