### ISSUE TITLE
Using websockets to update the Lua server DataModel

### ISSUE THREAD

**Issue by Stefanuk12** [NightrainsRbx/RobloxLsp#171]
**Description**
Currently, the system uses HTTP requests to localserver on a port to update the DataModel which can lag on larger datamodels. It would be really nice and helpful if a new system is put into place - specifically with websockets, but likely can be done with HTTP too.

**My idea**
Instead of loading the entire DataModel at once, load it dynamically and store it in cache. For example, on VSC, I type workspace.Model and it would ask the websocket to get the children of their model - their path and type. Whilst this may cause a tiny hiccup, it should be minimal due to the cache. We are also **not** getting the descendants so it would be even less laggy.

Another idea is instead of sending the entire DataModel, send the changes instead. This would minimise bandwidth used and lag since each time an update is sent, the entire tree is rebuilt (on the plugin).

**Comment by NightrainsRbx** [comment]
I like the first idea, but I would require asking the websocket for children every time you index something since we never know when something has changed, the cache wouldn't work very well.

Also, Roblox LSP recompiles the workspace every time the DataModel changes, this won't be possible with the first idea, although it would only affect type-checking.

I think updating the data dynamically is the way to go, besides, the problems you may have with lag may be due to how the data is compiled after receiving it from the plugin, it recompiles the entire roblox API, since children data is part of it, but this can be done much better and needs to be changed before anything else.

I have a doubt, do you have lag on Roblox Studio or on VSCode? Also, I always recommend blacklisting instances that contain too many descendants, like the workspace, this can be done in the plugin settings.

**Comment by Stefanuk12** [comment]
Thank you for the reply. I am lagging within Studio unfortunately but with your suggestion it eases it. But yeah, perhaps some optimisations are needed. The reason I suggested a cache was because I saw the entire data model getting refreshed in the Update function.
