### ISSUE TITLE
[Suggestion] Add support for Intellij

### ISSUE THREAD

**Issue by keplerHaloxx** [NightrainsRbx/RobloxLsp#235]
I would like to use IntelliJ instead of Visual Studio Code as it is what I like better. Can you add this?

**Comment by NightrainsRbx** [comment]
Support for a code editor would require a different client and a different repository, this repository it's only for the VSCode client + the server.

Support for Intellij could be easily achieved since this is a Language Server, and it's not specific for any code editor, a LSP client it's the only thing that you need, and it probably exists already.
