### ISSUE TITLE
Highlight function return types as types

### ISSUE THREAD

**Issue by Dekkonot** [NightrainsRbx/RobloxLsp#27]
The expectation would be that in this snippet, `qux` would be highlight the same as `baz`:

![image](https://user-images.githubusercontent.com/4625546/99849850-20e1e880-2b31-11eb-85db-aa0f36d671dd.png)

This is not the case (even with semantic highlighting), so it should be fixed.

**Comment by NightrainsRbx** [comment]
This should only work with semantic highlighting, because grammars are only for colorizing hover (because it's too complicated to me).
![image](https://user-images.githubusercontent.com/69439321/99850915-37e20400-2b4c-11eb-86ec-87bd7e5afc86.png)

And it seems that it does work for me, even with the One Dark Pro theme.
![image](https://user-images.githubusercontent.com/69439321/99851051-72e43780-2b4c-11eb-9282-ad442345ba75.png)

**Comment by Dekkonot** [comment]
Right. That's strange. I can try reinstalling the theme, I guess.

**Comment by Dekkonot** [comment]
That fixed it. Sorry!
