### ISSUE TITLE
Module code do not return exactly one value.

### ISSUE THREAD

**Issue by TheInspector556** [NightrainsRbx/RobloxLsp#39]
![image](https://user-images.githubusercontent.com/76826756/107844004-87953c00-6dd8-11eb-8b8b-b3fa7ca2c49f.png)

**Comment by TheInspector556** [comment]
and If I remove the ; it still doesnt work

**Comment by TheInspector556** [comment]
![image](https://user-images.githubusercontent.com/76826756/107844029-c0351580-6dd8-11eb-91b2-c43b4a0481d3.png)

**Comment by NightrainsRbx** [comment]
I don't see your problem, the diagnostic has nothing to do with the semicolon.

That warning says that you need to return a value in the ModuleScript code, it thinks it is a ModuleScript since Rojo syncs the files that ends with .lua as ModuleScripts.

You can disable it in the settings if you don't want it.

**Comment by jaime-a-vives** [comment]
Are you sure this is Roblox LSP? I want this feature - when I forget to return in a module, I get notified from Roblox instead of VSCode
