### ISSUE TITLE
Specify a function as a recursive module loader

### ISSUE THREAD

**Issue by OttoHatt** [NightrainsRbx/RobloxLsp#68]
It seems very common (w/ Nevermore, Knit, and a lot of custom solutions I've seen) for people to use custom module loaders that recursively search for a module given a string.

This is how you'd get intellisense for a module w/ Nevermore:
```lua
local require = require(game:GetService("ReplicatedStorage"):WaitForChild("Nevermore"))

---@module src.modules.Utility.Maid
local Maid = require("Maid")

-- Now intellisense finds :GiveTask() / :Destroy() etc...
```

However, it can get cumbersome to add a statement for each module. This could be fixed by searching for `Nevermore`, or checking for using require with a string, etc. However this isn't versatile.

A good solution could be a tag like this, which only applies to functions that are passed strings.
```lua
---@moduleloader <list of relative source directories, searched recursively>
local loader = function(inString) end
```
```lua
---@moduleloader src.modules src.more_modules
local require = require(game:GetService("ReplicatedStorage"):WaitForChild("Nevermore"))

local Maid = require("Maid")
-- Now intellisense finds :GiveTask() / :Destroy() etc...
```
```lua
---@moduleloader src.modules src.more_modules
local loader = require(game:GetService("ReplicatedStorage"):WaitForChild("Nevermore"))

local Maid  = loader("Maid")
```

This could cause some weird conflicts. For example, several modules with the same name. To fix this, you could allow `---@module` to override any assumptions made by ```---@moduleloader```.

This seems like a pretty good compromise between ease of use and control?

**Comment by NightrainsRbx** [comment]
That's a cool idea, and is definitely possible, but this problem already has a solution that will be available soon when I update the language server, a feature called plugins that you can already try in sumneko's lua-language-server, there is a wiki for it https://github.com/sumneko/lua-language-server/wiki/Plugin.

With this you can automatically add the comment `---@module` on top require functions with string patterns, only for the language server to read it.

I have already updated Roblox LSP but I have not released it yet because I am implementing some cool features.
