### ISSUE TITLE
EmmyLua class annotation, type detection and auto complete is broken since 1.0.0++

### ISSUE THREAD

**Issue by ldhongen1990** [NightrainsRbx/RobloxLsp#88]
@NightrainsRbx  Didn't work since the upgrade from 0.15.11 to 1.0.0++

Before upgrade and working (0.15.11), type detection and auto complete works:
![image](https://user-images.githubusercontent.com/17633734/133056367-752cb16e-e73c-4cb9-8508-f32d89e33943.png)

After upgrade (1.0.0++), EmmyLua type detection and auto complete broken:
![image](https://user-images.githubusercontent.com/17633734/133056456-b07fb50c-9003-4513-85e1-ab33dc80fc1f.png)

Will love to have it working again.

Edit:
P.S the EmmyLua standalone extension was not installed in my vscode, only RobloxLSP because it comes bundled with EmmyLua.

**Comment by NightrainsRbx** [comment]
EmmyLua types are not compatible with Luau types, you can't do `---@class Class` and `local class: Class` because they are two different kinds of types, with EmmyLua annotations, you would have to do:
```lua
---@type ClassA
local MyClassA = nil
```

You can also use instead only Luau types, and define a type alias for `ClassA`, which could be for example:
```lua
local ClassA = {}
type ClassA = typeof(ClassA)
```
